import { z } from 'zod';
import seed from '../../public/content.json';
export const safeUrl = (s: string) => !s || /^https:\/\/[^\s]+$/i.test(s) || /^media\/[a-zA-Z0-9.-]+$/.test(s) || /^mailto:[^\s@]+@[^\s@]+$/.test(s);
const url = z.string().max(2000).refine(safeUrl);
export const linkSchema = z.object({label:z.string().max(80),url});
export const figureSchema = z.object({src:url,alt:z.string().max(1000),caption:z.string().max(1000),sourceLabel:z.string().max(400),sourceUrl:url});
export const itemSchema = z.object({id:z.string().min(1).max(100),title:z.string().max(400),text:z.string().max(6000),authors:z.string().max(2000),meta:z.string().max(300),demo:z.enum(['antagonist','joint','running','coil','curve','lights','none']),mediaType:z.enum(['image','video']),media:url,caption:z.string().max(600),links:z.array(linkSchema).max(10),layout:z.enum(['left','right','wide']),figure:figureSchema.optional()});
export const sectionSchema = z.object({id:z.string().min(1).max(100),title:z.string().max(200),intro:z.string().max(3000),page:z.enum(['home','research']).default('home'),items:z.array(itemSchema).max(500)});
export const siteSchema = z.object({name:z.string().min(1).max(120),field:z.string().max(200),affiliation:z.string().max(400),bio:z.string().max(6000),portrait:url,links:z.array(linkSchema).max(10),sections:z.array(sectionSchema).max(20)}).superRefine((s,ctx)=>{const ids=s.sections.flatMap(x=>[x.id,...x.items.map(i=>i.id)]);if(new Set(ids).size!==ids.length)ctx.addIssue({code:z.ZodIssueCode.custom,message:'Section and item IDs must be unique.'});});
export type SiteContent = z.infer<typeof siteSchema>;
export type Item = z.infer<typeof itemSchema>;
export type Section = z.infer<typeof sectionSchema>;
export const blankItem = ():Item => ({id:crypto.randomUUID(),title:'New research entry',text:'',authors:'',meta:'',demo:'none',mediaType:'image',media:'',caption:'',links:[],layout:'left'});
export const initialContent:SiteContent = siteSchema.parse(seed);
