'use client';
import {useEffect,useState} from 'react';
import {Slider} from '@/components/ui/slider';
import {Play,Pause} from 'lucide-react';
export default function Demo({kind}:{kind:'coil'|'curve'|'lights'}){
 const [value,setValue]=useState(kind==='coil'?42:kind==='curve'?4:50),[phase,setPhase]=useState(0),[playing,setPlaying]=useState(false);
 useEffect(()=>{if(!playing)return;const t=setInterval(()=>setPhase(p=>(p+.055)%(Math.PI*2)),50);return()=>clearInterval(t);},[playing]);
 if(kind==='coil'){
  const a=value*Math.PI/180,L=258*Math.cos(a),R=258*Math.sin(a)/(2*Math.PI*5),x=160-L/2;
  const path=Array.from({length:301},(_,i)=>`${i?'L':'M'}${(x+L*i/300).toFixed(2)},${(85+R*Math.sin(i/300*10*Math.PI)).toFixed(2)}`).join(' ');
  return <div className="demo"><div className="demo-label">HELIX GEOMETRY <span>Interactive</span></div><svg viewBox="0 0 320 177" role="img" aria-label={`Coiled fiber with a ${value} degree angle to the axis`}><path d="M22 85H298" className="axis dashed"/><path d={path} fill="none" stroke="#245f8e" strokeWidth="3"/><path d={`M${x} 63v61 M${x+L} 63v61 M${x} 116h${L}`} className="dimension"/><text x="160" y="139" textAnchor="middle">Axial length / fiber length = {Math.cos(a).toFixed(2)}</text><text x="160" y="161" textAnchor="middle" className="svg-note">Fixed fiber length and five turns</text></svg><div className="demo-control"><label>Helix angle <strong>{value}°</strong></label><Slider aria-label="Helix angle in degrees to the axis" min={15} max={70} step={1} value={[value]} onValueChange={v=>setValue(v[0])}/></div><details><summary>About this sketch</summary><p>Geometry only: z = ℓ cos α and R = ℓ sin α / (2πN), where α is measured from the axis. This does not predict thermal contraction or force.</p></details></div>;
 }
 if(kind==='curve'){
  const f=(x:number)=>(Math.exp(value*x)-1)/(Math.exp(value)-1);
  const path=Array.from({length:101},(_,i)=>`${i?'L':'M'}${42+i*2.35},${139-110*f(i/100)}`).join(' ');
  return <div className="demo"><div className="demo-label">NONLINEAR ELASTICITY <span>Interactive</span></div><svg viewBox="0 0 320 177" role="img" aria-label={`Illustrative normalized J-curve, shape parameter ${value.toFixed(1)}`}><path d="M42 24v115h245" className="axis"/><path d="M42 29h235M42 84h235" className="grid-line"/><path d="M42 139L277 29" className="axis dashed"/><path d={path} stroke="#245f8e" fill="none" strokeWidth="3"/><text x="166" y="164" textAnchor="middle">Normalized extension</text><text transform="translate(16 89) rotate(-90)" textAnchor="middle">Normalized force</text><text x="32" y="143">0</text><text x="275" y="153">1</text><text x="29" y="33">1</text></svg><div className="demo-control"><label>Curve shape <strong>k = {value.toFixed(1)}</strong></label><Slider aria-label="J-curve shape parameter" min={.5} max={8} step={.1} value={[value]} onValueChange={v=>setValue(v[0])}/></div><details><summary>About this sketch</summary><p>Illustrative family: f(x) = (exp(kx) − 1) / (exp(k) − 1), with 0 ≤ x ≤ 1. A visual explanation of strain stiffening, not a fitted or validated constitutive law.</p></details></div>;
 }
 return <div className="demo lights-demo"><div className="demo-label">32-ACTUATOR ARRAY <button onClick={()=>setPlaying(p=>!p)} aria-label={playing?'Pause light array':'Play light array'}>{playing?<Pause size={12}/>:<Play size={12}/>} {playing?'Pause':'Play'}</button></div><svg viewBox="0 0 320 177" role="img" aria-label="Illustrative traveling wave across 32 suspended lights"><path d="M21 32h278" className="axis"/>{Array.from({length:32},(_,i)=>{const x=26+i*8.65,y=93+value*.56*Math.sin(i/31*2*Math.PI-phase);return <g key={i}><path d={`M${x} 33V${y}`} stroke="#9ba9b5" strokeWidth=".8"/><circle cx={x} cy={y} r="3.1" fill="#245f8e"/></g>;})}<text x="25" y="157">m0</text><text x="270" y="157">m31</text><text x="160" y="157" textAnchor="middle" className="svg-note">Traveling-wave concept</text></svg><div className="demo-control"><label>Wave amplitude <strong>{value}%</strong></label><Slider aria-label="Light wave amplitude" min={0} max={100} step={1} value={[value]} onValueChange={v=>setValue(v[0])}/></div><details><summary>About this sketch</summary><p>Prescribed motion: yᵢ = y₀ + A sin(2πi/31 − φ). This animation illustrates coordinated motion; it does not simulate actuator heating, lag, or drift.</p></details></div>;
}
