'use client';
import {useEffect,useRef,useState,type PointerEvent} from 'react';
import {GripVertical,ArrowUp,ArrowDown,Pencil,Plus,Trash2,Undo2,Check,Eye,Upload,X} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Toaster} from '@/components/ui/sonner';
import {toast} from 'sonner';
import {initialContent,blankItem,siteSchema,type SiteContent,type Section,type Item} from '@/lib/content';
import Demo from './demos';
import {loadPage,stageMedia,exportWebsite,mediaSource} from './static-files';
type Form = {kind:'profile';value:SiteContent}|{kind:'section';value:Section;isNew?:boolean}|{kind:'item';value:Item;section:string;isNew?:boolean};
type Drag = {kind:'section'|'item';id:string;section?:string;x:number;y:number;active:boolean};
function Links({links}:{links:Item['links']}){return <div className="links">{links.filter(l=>l.url&&l.label).map((l,i)=><a key={i} href={l.url} target="_blank" rel="noreferrer">{l.label}</a>)}</div>;}
function Field({label,value,onChange,multiline=false}:{label:string;value:string;onChange:(v:string)=>void;multiline?:boolean}){return <label className="field"><span>{label}</span>{multiline?<Textarea value={value} onChange={e=>onChange(e.target.value)} rows={4}/>:<Input value={value} onChange={e=>onChange(e.target.value)}/>}</label>;}
function Choice({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:[string,string][]}){return <label className="field"><span>{label}</span><Select value={value} onValueChange={onChange}><SelectTrigger className="w-full" aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{options.map(([v,t])=><SelectItem key={v} value={v}>{t}</SelectItem>)}</SelectContent></Select></label>;}
export default function Portfolio({canEdit}:{canEdit:boolean}){
 const [content,setContent]=useState<SiteContent>(initialContent),[saved,setSaved]=useState<SiteContent>(initialContent),[revision,setRevision]=useState(0),[loaded,setLoaded]=useState(false),[loadError,setLoadError]=useState(''),[editing,setEditing]=useState(canEdit),[saving,setSaving]=useState(false),[history,setHistory]=useState<SiteContent[]>([]),[form,setForm]=useState<Form|null>(null),[uploading,setUploading]=useState(false),[drop,setDrop]=useState(''),[dragging,setDragging]=useState('');
 const drag=useRef<Drag|null>(null),dropRef=useRef<{section:string;item?:string}|null>(null),file=useRef<HTMLInputElement>(null);
 const dirty=JSON.stringify(content)!==JSON.stringify(saved);
 const stateRef=useRef({content,editing});stateRef.current={content,editing};
 async function load(){setLoadError('');setLoaded(false);try{const parsed=await loadPage();setContent(parsed);setSaved(parsed);setLoaded(true);}catch(e){setLoadError(e instanceof Error?e.message:'The page could not be loaded.');}}
 useEffect(()=>{void load();},[]);
 useEffect(()=>{if(!dirty)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 useEffect(()=>{document.title=content.name+' | Mechanics & Soft Robotics';},[content.name]);
 function change(next:SiteContent){setHistory(h=>[...h.slice(-19),content]);setContent(next);}
 function sectionChange(id:string,fn:(s:Section)=>Section){change({...content,sections:content.sections.map(s=>s.id===id?fn(s):s)});}
 function moveSection(id:string,to:number){const all=[...content.sections],from=all.findIndex(s=>s.id===id);if(from<0||to<0||to>=all.length)return;all.splice(to,0,all.splice(from,1)[0]);change({...content,sections:all});}
 function moveItem(section:string,id:string,to:number){sectionChange(section,s=>{const a=[...s.items],from=a.findIndex(i=>i.id===id);if(from<0||to<0||to>=a.length)return s;a.splice(to,0,a.splice(from,1)[0]);return {...s,items:a};});}
 function startDrag(e:PointerEvent<HTMLButtonElement>,d:Omit<Drag,'x'|'y'|'active'>){if(e.button!==0)return;e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);drag.current={...d,x:e.clientX,y:e.clientY,active:false};}
 function pointerMove(e:PointerEvent<HTMLButtonElement>){const d=drag.current;if(!d)return;if(!d.active&&Math.hypot(e.clientX-d.x,e.clientY-d.y)<6)return;d.active=true;setDragging(d.id);const el=document.elementFromPoint(e.clientX,e.clientY),section=el?.closest<HTMLElement>('[data-section]'),item=el?.closest<HTMLElement>('[data-item]');dropRef.current=section?{section:section.dataset.section!,item:item?.dataset.item}:null;setDrop((d.kind==='section'?section?.dataset.section:item?.dataset.item??section?.dataset.section)??'');if(e.clientY<90)window.scrollBy(0,-16);else if(e.clientY>window.innerHeight-90)window.scrollBy(0,16);}
 function endDrag(){const d=drag.current,target=dropRef.current;if(d?.active&&target){if(d.kind==='section'){const to=content.sections.findIndex(s=>s.id===target.section);moveSection(d.id,to);}else if(target.item!==d.id){const source=content.sections.find(s=>s.id===d.section)?.items.find(i=>i.id===d.id);if(source){const sections=content.sections.map(s=>({...s,items:s.items.filter(i=>i.id!==d.id)}));const dest=sections.find(s=>s.id===target.section);if(dest){const idx=target.item?dest.items.findIndex(i=>i.id===target.item):-1;dest.items.splice(idx<0?dest.items.length:idx,0,source);change({...content,sections});}}}}drag.current=null;dropRef.current=null;setDrop('');setDragging('');}
 const grip=(kind:'section'|'item',id:string,section?:string)=><button className="icon-button grip" title="Drag to reorder; use arrow buttons to move with a keyboard" aria-label={`Drag ${kind}`} onPointerDown={e=>startDrag(e,{kind,id,section})} onPointerMove={pointerMove} onPointerUp={endDrag} onPointerCancel={()=>{drag.current=null;setDrop('');setDragging('');}}><GripVertical size={16}/></button>;
 async function save(){setSaving(true);try{await exportWebsite(content);setSaved(content);toast.success('Website downloaded. Extract the ZIP and commit its contents to your GitHub repository.',{duration:10000});}catch(e){toast.error(e instanceof Error?e.message:'Export failed. Your draft is still here.',{duration:8000});}finally{setSaving(false);}}
 function applyForm(){if(!form)return;let next=content;if(form.kind==='profile'){next={...form.value,sections:content.sections};}else if(form.kind==='section'){next={...content,sections:form.isNew?[...content.sections,form.value]:content.sections.map(s=>s.id===form.value.id?form.value:s)};}else{next={...content,sections:content.sections.map(s=>s.id===form.section?{...s,items:form.isNew?[...s.items,form.value]:s.items.map(i=>i.id===form.value.id?form.value:i)}:s)};}const checked=siteSchema.safeParse(next);if(!checked.success){toast.error('Check your content lengths and links. Website links must start with https://.');return;}change(checked.data);setForm(null);}
 function updateForm(key:string,value:unknown){setForm(f=>f?{...f,value:{...f.value,[key]:value}} as Form:f);}
 async function upload(f:File){if(!form)return;if(form.kind==='profile'&&!f.type.startsWith('image/')){toast.error('Choose an image for the portrait.');return;}setUploading(true);try{const d=await stageMedia(f);setForm(current=>{if(!current)return null;if(current.kind==='profile')return {...current,value:{...current.value,portrait:d.url}};if(current.kind==='item')return {...current,value:{...current.value,media:d.url,mediaType:d.type}};return current;});toast.success('Media added to this draft. Export the website to keep it.');}catch(e){toast.error(e instanceof Error?e.message:'File could not be added.');}finally{setUploading(false);}}
 useEffect(()=>{
  const context=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:unknown)=>void|Promise<void>}}).modelContext;if(!context)return;const lifecycle=new AbortController();
  try{void Promise.resolve(context.registerTool({name:'read_portfolio',description:'Read the currently visible academic portfolio and whether the editor is open.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>({content:stateRef.current.content,editing:stateRef.current.editing})},{signal:lifecycle.signal})).catch(e=>console.warn('Agent tools unavailable',e));
   if(canEdit)void Promise.resolve(context.registerTool({name:'start_portfolio_editing',description:'Open the portfolio editor. Does not change or save content.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('Expected an empty object.');setEditing(true);return {editor:'open',saved:false};}},{signal:lifecycle.signal})).catch(e=>console.warn('Agent tools unavailable',e));
  }catch(e){console.warn('Agent tools unavailable',e);}return()=>lifecycle.abort();
 },[canEdit]);
 return <><Toaster position="bottom-right"/><a className="skip-link" href="#main">Skip to content</a><div className="topbar"><a href="#" className="wordmark">LC<span> / Research</span></a><nav aria-label="Main navigation">{content.sections.map(s=><a key={s.id} href={'#'+s.id}>{s.title}</a>)}</nav>{canEdit?<button className="edit-toggle" disabled={!loaded} onClick={()=>setEditing(e=>!e)}>{editing?<Eye size={14}/>:<Pencil size={14}/>} {editing?'Preview':'Edit page'}</button>:<a className="editor-signin" href="./editor.html">Edit a copy</a>}</div>
 {canEdit&&(editing||dirty)&&<div className="editor-bar"><div><strong>{editing?'Editing your page':'Previewing your changes'}</strong><span>{dirty?'Draft changes in this tab':'Export to publish on GitHub'}</span></div><div className="editor-actions">{editing&&<><button onClick={()=>{const last=history.at(-1);if(last){setContent(last);setHistory(h=>h.slice(0,-1));}}} disabled={!history.length||saving}><Undo2 size={15}/>Undo</button><button onClick={()=>setForm({kind:'section',value:{id:crypto.randomUUID(),title:'New section',intro:'',items:[]},isNew:true})}><Plus size={15}/>Section</button></>}<Button onClick={save} disabled={!loaded||saving}>{saving?'Preparing…':<><Check size={14}/>Download website</>}</Button></div>{editing&&<p>Drag the handles or use the arrows. Drafts stay in this tab. Download the website, extract the ZIP, and commit the files to your GitHub repository to publish.</p>}</div>}
 <main id="main" className={editing?'page editing':'page'} aria-busy={!loaded&&!loadError}>{loadError?<div className="load-error" role="alert">{loadError}<button onClick={load}>Retry</button></div>:!loaded&&<p className="loading-note">Loading website…</p>}
 <header className={'intro '+(content.portrait?'with-portrait':'')}><div><p className="research-field">{content.field}</p><h1>{content.name}</h1><p className="affiliation">{content.affiliation}</p><div className="bio">{content.bio.split('\n\n').map((p,i)=><p key={i}>{p}</p>)}</div><Links links={content.links}/>{editing&&<button className="inline-edit" onClick={()=>setForm({kind:'profile',value:structuredClone(content)})}><Pencil size={14}/>Edit introduction & links</button>}</div>{content.portrait&&<img className="portrait" src={mediaSource(content.portrait)} alt={content.name}/>}</header>
 {content.sections.map((section,si)=><section id={section.id} data-section={section.id} key={section.id} className={'content-section '+(drop===section.id?'drop-target ':'')+(dragging===section.id?'dragging':'')}><div className="section-heading"><h2>{section.title}</h2>{editing&&<div className="section-tools">{grip('section',section.id)}<button className="icon-button" aria-label={'Move '+section.title+' up'} disabled={si===0} onClick={()=>moveSection(section.id,si-1)}><ArrowUp size={15}/></button><button className="icon-button" aria-label={'Move '+section.title+' down'} disabled={si===content.sections.length-1} onClick={()=>moveSection(section.id,si+1)}><ArrowDown size={15}/></button><button className="icon-button" aria-label={'Edit '+section.title} onClick={()=>setForm({kind:'section',value:structuredClone(section)})}><Pencil size={15}/></button><button className="icon-button" aria-label={'Remove '+section.title} onClick={()=>{change({...content,sections:content.sections.filter(s=>s.id!==section.id)});toast('Section removed. Use Undo to restore it.');}}><Trash2 size={15}/></button></div>}</div>{section.intro&&<p className="section-intro">{section.intro}</p>}
 {section.items.map((item,ii)=>{const hasMedia=item.media||item.demo!=='none';return <article key={item.id} data-item={item.id} className={`entry ${hasMedia?'has-media':'text-entry'} layout-${item.layout} ${drop===item.id?'drop-target':''} ${dragging===item.id?'dragging':''}`}>{editing&&<div className="entry-tools">{grip('item',item.id,section.id)}<button className="icon-button" aria-label={'Move '+item.title+' up'} disabled={ii===0} onClick={()=>moveItem(section.id,item.id,ii-1)}><ArrowUp size={14}/></button><button className="icon-button" aria-label={'Move '+item.title+' down'} disabled={ii===section.items.length-1} onClick={()=>moveItem(section.id,item.id,ii+1)}><ArrowDown size={14}/></button><button onClick={()=>setForm({kind:'item',value:structuredClone(item),section:section.id})}><Pencil size={13}/>Edit entry</button><button className="icon-button" aria-label={'Remove '+item.title} onClick={()=>{sectionChange(section.id,s=>({...s,items:s.items.filter(i=>i.id!==item.id)}));toast('Entry removed. Use Undo to restore it.');}}><Trash2 size={14}/></button></div>}{hasMedia&&<figure className="entry-media">{item.media?(item.mediaType==='video'?<video src={mediaSource(item.media)} controls playsInline preload="metadata" aria-label={item.caption||item.title}/>:<img src={mediaSource(item.media)} alt={item.caption||item.title} loading="lazy"/>):<Demo kind={item.demo as 'coil'|'curve'|'lights'}/>} {item.caption&&<figcaption>{item.caption}</figcaption>}</figure>}<div className="entry-copy">{hasMedia&&item.meta&&<p className="topic">{item.meta}</p>}<h3>{item.title}</h3>{item.authors&&<p className="authors">{item.authors.split(/(Liuyang Cheng)/g).map((s,i)=>s==='Liuyang Cheng'?<strong key={i}>{s}</strong>:s)}</p>}{!hasMedia&&item.meta&&<p className="venue">{item.meta}</p>}{item.text&&<p className="entry-description">{item.text}</p>}<Links links={item.links}/></div></article>;})}
 {editing&&<button className="add-entry" onClick={()=>setForm({kind:'item',section:section.id,value:blankItem(),isNew:true})}><Plus size={15}/>Add an entry</button>}
 </section>)}
 <footer><span>© {new Date().getFullYear()} {content.name}</span><a href="#">Back to top</a></footer></main>
 <Dialog open={!!form} onOpenChange={open=>{if(!open&&!uploading)setForm(null);}}><DialogContent className="edit-dialog"><DialogHeader><DialogTitle>{form?.kind==='profile'?'Edit introduction':form?.kind==='section'?'Edit section':'Edit research entry'}</DialogTitle><DialogDescription>Apply to preview your changes, then download the website to keep them.</DialogDescription></DialogHeader>{form&&<form onSubmit={e=>{e.preventDefault();applyForm();}} className="edit-form">
 {form.kind==='profile'?<><Field label="Name" value={form.value.name} onChange={v=>updateForm('name',v)}/><Field label="Research areas" value={form.value.field} onChange={v=>updateForm('field',v)}/><Field label="Affiliation" value={form.value.affiliation} onChange={v=>updateForm('affiliation',v)}/><Field label="Biography" value={form.value.bio} multiline onChange={v=>updateForm('bio',v)}/></>:<><Field label="Title" value={form.value.title} onChange={v=>updateForm('title',v)}/>{form.kind==='section'?<Field label="Section introduction" value={form.value.intro} multiline onChange={v=>updateForm('intro',v)}/>:<><Field label="Description" value={form.value.text} multiline onChange={v=>updateForm('text',v)}/><Field label="Authors" value={form.value.authors} onChange={v=>updateForm('authors',v)}/><Field label="Topic or venue and year" value={form.value.meta} onChange={v=>updateForm('meta',v)}/><div className="form-columns"><Choice label="Demo sketch" value={form.value.demo} onChange={v=>updateForm('demo',v)} options={[["none","No sketch"],["coil","Helix geometry"],["curve","J-curve"],["lights","32-light array"]]}/><Choice label="Media placement" value={form.value.layout} onChange={v=>updateForm('layout',v)} options={[["left","Left of text"],["right","Right of text"],["wide","Full width above text"]]}/></div></>}</>}
 {form.kind!=='section'&&<><div className="media-upload" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const f=e.dataTransfer.files[0];if(f&&!uploading)void upload(f);}}><Upload size={21}/><strong>{form.kind==='profile'?'Portrait photo':'Image, GIF, or video'}</strong><span>Drop a file here or choose one · up to 25 MB</span><input ref={file} type="file" accept={form.kind==='profile'?'image/jpeg,image/png,image/webp,image/gif':'image/jpeg,image/png,image/webp,image/gif,video/mp4,video/webm'} hidden onChange={e=>{if(e.target.files?.[0])void upload(e.target.files[0]);e.target.value='';}}/><button type="button" disabled={uploading} onClick={()=>file.current?.click()}>{uploading?'Uploading…':'Choose file'}</button></div><Field label={form.kind==='profile'?'Portrait URL (optional)':'Media URL (optional; replaces the sketch)'} value={form.kind==='profile'?form.value.portrait:form.value.media} onChange={v=>updateForm(form.kind==='profile'?'portrait':'media',v)}/>{form.kind==='item'&&<><Choice label="Media type" value={form.value.mediaType} onChange={v=>updateForm('mediaType',v)} options={[["image","Image / GIF"],["video","Video (MP4 / WebM)"]]}/><Field label="Caption / accessible description" value={form.value.caption} onChange={v=>updateForm('caption',v)}/></>}<div className="link-editor"><h4>Links</h4>{form.value.links.map((link,i)=><div className="link-row" key={i}><Input aria-label={'Link '+(i+1)+' label'} placeholder="Label, e.g. Paper" value={link.label} onChange={e=>updateForm('links',form.value.links.map((l,j)=>j===i?{...l,label:e.target.value}:l))}/><Input aria-label={'Link '+(i+1)+' URL'} placeholder="https://…" value={link.url} onChange={e=>updateForm('links',form.value.links.map((l,j)=>j===i?{...l,url:e.target.value}:l))}/><button type="button" className="icon-button" aria-label={'Remove link '+(i+1)} onClick={()=>updateForm('links',form.value.links.filter((_,j)=>j!==i))}><X size={14}/></button></div>)}<button type="button" disabled={form.value.links.length>=10} onClick={()=>updateForm('links',[...form.value.links,{label:'',url:''}])}><Plus size={14}/>Add link</button></div></>}
 <div className="form-actions"><button type="button" disabled={uploading} onClick={()=>setForm(null)}>Cancel</button><Button type="submit" disabled={uploading}>Apply changes</Button></div></form>}</DialogContent></Dialog>
 </>;
}
