'use client';
import {useEffect,useRef,useState,type PointerEvent} from 'react';
import {GripVertical,ArrowUp,ArrowDown,Pencil,Plus,Trash2,Undo2,Check,Eye,Upload,X} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Toaster} from '@/components/ui/sonner';
import {toast} from 'sonner';
import {initialContent,blankItem,siteSchema,type SiteContent,type Section,type Item} from '@/lib/content';
import ProjectMedia from './project-media';
import {loadPage,stageMedia,exportWebsite,mediaSource,saveDraft,loadDraft,clearDraft} from './static-files';
import {publishWebsite} from './github-publish';
type Form = {kind:'profile';value:SiteContent}|{kind:'section';value:Section;isNew?:boolean}|{kind:'item';value:Item;section:string;isNew?:boolean};
type Drag = {kind:'section'|'item';id:string;section?:string;x:number;y:number;active:boolean};
function Links({links}:{links:Item['links']}){return <div className="links">{links.filter(l=>l.url&&l.label).map((l,i)=><a key={i} href={l.url} target="_blank" rel="noreferrer">{l.label}</a>)}</div>;}
function Field({label,value,onChange,multiline=false}:{label:string;value:string;onChange:(v:string)=>void;multiline?:boolean}){return <label className="field"><span>{label}</span>{multiline?<Textarea value={value} onChange={e=>onChange(e.target.value)} rows={4}/>:<Input value={value} onChange={e=>onChange(e.target.value)}/>}</label>;}
function Choice({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:[string,string][]}){return <label className="field"><span>{label}</span><Select value={value} onValueChange={onChange}><SelectTrigger className="w-full" aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{options.map(([v,t])=><SelectItem key={v} value={v}>{t}</SelectItem>)}</SelectContent></Select></label>;}
export default function Portfolio({canEdit}:{canEdit:boolean}){
 const [content,setContent]=useState<SiteContent>(initialContent),[saved,setSaved]=useState<SiteContent>(initialContent),[loaded,setLoaded]=useState(false),[loadError,setLoadError]=useState(''),[editing,setEditing]=useState(canEdit),[saving,setSaving]=useState(false),[history,setHistory]=useState<SiteContent[]>([]),[form,setForm]=useState<Form|null>(null),[uploading,setUploading]=useState(false),[drop,setDrop]=useState(''),[dragging,setDragging]=useState('');
 const [draftStatus,setDraftStatus]=useState<'loading'|'saving'|'saved'|'error'>('loading'),[draftError,setDraftError]=useState(''),[publishOpen,setPublishOpen]=useState(false),[token,setToken]=useState(''),[publishing,setPublishing]=useState(false),[publishProgress,setPublishProgress]=useState(''),[publishError,setPublishError]=useState(''),[commitUrl,setCommitUrl]=useState(''),[discardOpen,setDiscardOpen]=useState(false),[discarding,setDiscarding]=useState(false);
 const restoreFailed=useRef(false),persistVersion=useRef(0),latestPublished=useRef<SiteContent>(initialContent);
 const drag=useRef<Drag|null>(null),dropRef=useRef<{section:string;item?:string}|null>(null),file=useRef<HTMLInputElement>(null);
 const [page,setPage]=useState<'home'|'research'>(window.location.pathname.endsWith('/research.html')||new URLSearchParams(window.location.search).get('page')==='research'?'research':'home');
 const visibleSections=content.sections.filter(s=>s.page===page);
 function navigate(next:'home'|'research',anchor=''){setPage(next);requestAnimationFrame(()=>{if(anchor)document.getElementById(anchor)?.scrollIntoView();else window.scrollTo(0,0);});}
 const dirty=JSON.stringify(content)!==JSON.stringify(saved);
 const stateRef=useRef({content,editing});stateRef.current={content,editing};
 async function load(){
  setLoadError('');setLoaded(false);setDraftError('');restoreFailed.current=false;
  const [live,draft]=await Promise.allSettled([loadPage(),canEdit?loadDraft():Promise.resolve(null)]);
  const restored=draft.status==='fulfilled'?draft.value:null;
  if(live.status==='fulfilled')latestPublished.current=live.value;
  if(restored){if(live.status==='rejected')latestPublished.current=restored.base;setContent(restored.content);setSaved(restored.base);setDraftStatus('saved');setLoaded(true);if(live.status==='rejected')setLoadError('The published site could not be checked. Your saved draft is available.');}
  else if(live.status==='fulfilled'){setContent(live.value);setSaved(live.value);setLoaded(true);}
  else setLoadError('The website could not be loaded. Please check your connection and retry.');
  if(draft.status==='rejected'){restoreFailed.current=true;setDraftStatus('error');setDraftError('Your browser could not restore the saved draft. Download a backup before closing this page.');}
 }
 useEffect(()=>{void load();},[]);
 useEffect(()=>{
  if(!canEdit||!loaded)return;if(restoreFailed.current){setDraftStatus('error');return;}
  const version=++persistVersion.current;setDraftStatus('saving');
  void saveDraft(content,saved).then(()=>{if(version===persistVersion.current){setDraftStatus('saved');setDraftError('');}}).catch(()=>{if(version===persistVersion.current){setDraftStatus('error');setDraftError('This browser could not save your draft. Keep this tab open and download a backup.');}});
 },[content,saved,canEdit,loaded]);
 useEffect(()=>{if(!canEdit||(!publishing&&!(dirty&&draftStatus!=='saved')&&!form))return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[canEdit,dirty,draftStatus,publishing,form]);
 useEffect(()=>{document.title=(page==='research'?'Research | ':'')+content.name+' | Mechanics & Soft Robotics';},[content.name,page]);
 function change(next:SiteContent){if(!loaded||publishing||discarding)return;setCommitUrl('');setDraftStatus('saving');setHistory(h=>[...h.slice(-19),content]);setContent(next);}
 function sectionChange(id:string,fn:(s:Section)=>Section){change({...content,sections:content.sections.map(s=>s.id===id?fn(s):s)});}
 function moveSection(id:string,to:number){const reordered=[...visibleSections],from=reordered.findIndex(s=>s.id===id);if(from<0||to<0||to>=reordered.length)return;reordered.splice(to,0,reordered.splice(from,1)[0]);let index=0;change({...content,sections:content.sections.map(s=>s.page===page?reordered[index++]:s)});}
 function moveItem(section:string,id:string,to:number){sectionChange(section,s=>{const a=[...s.items],from=a.findIndex(i=>i.id===id);if(from<0||to<0||to>=a.length)return s;a.splice(to,0,a.splice(from,1)[0]);return {...s,items:a};});}
 function startDrag(e:PointerEvent<HTMLButtonElement>,d:Omit<Drag,'x'|'y'|'active'>){if(e.button!==0)return;e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);drag.current={...d,x:e.clientX,y:e.clientY,active:false};}
 function pointerMove(e:PointerEvent<HTMLButtonElement>){const d=drag.current;if(!d)return;if(!d.active&&Math.hypot(e.clientX-d.x,e.clientY-d.y)<6)return;d.active=true;setDragging(d.id);const el=document.elementFromPoint(e.clientX,e.clientY),section=el?.closest<HTMLElement>('[data-section]'),item=el?.closest<HTMLElement>('[data-item]');dropRef.current=section?{section:section.dataset.section!,item:item?.dataset.item}:null;setDrop((d.kind==='section'?section?.dataset.section:item?.dataset.item??section?.dataset.section)??'');if(e.clientY<90)window.scrollBy(0,-16);else if(e.clientY>window.innerHeight-90)window.scrollBy(0,16);}
 function endDrag(){const d=drag.current,target=dropRef.current;if(d?.active&&target){if(d.kind==='section'){const to=visibleSections.findIndex(s=>s.id===target.section);moveSection(d.id,to);}else if(target.item!==d.id){const source=content.sections.find(s=>s.id===d.section)?.items.find(i=>i.id===d.id);if(source){const sections=content.sections.map(s=>({...s,items:s.items.filter(i=>i.id!==d.id)}));const dest=sections.find(s=>s.id===target.section);if(dest){const idx=target.item?dest.items.findIndex(i=>i.id===target.item):-1;dest.items.splice(idx<0?dest.items.length:idx,0,source);change({...content,sections});}}}}drag.current=null;dropRef.current=null;setDrop('');setDragging('');}
 const grip=(kind:'section'|'item',id:string,section?:string)=><button className="icon-button grip" title="Drag to reorder; use arrow buttons to move with a keyboard" aria-label={`Drag ${kind}`} onPointerDown={e=>startDrag(e,{kind,id,section})} onPointerMove={pointerMove} onPointerUp={endDrag} onPointerCancel={()=>{drag.current=null;setDrop('');setDragging('');}}><GripVertical size={16}/></button>;
 async function save(){setSaving(true);try{await exportWebsite(content);toast.success('Backup downloaded. Use Save to GitHub to update the public website.',{duration:8000});}catch(e){toast.error(e instanceof Error?e.message:'Export failed. Your draft is still here.',{duration:8000});}finally{setSaving(false);}}
 async function publish(){
  setPublishing(true);setPublishError('');setPublishProgress('Checking repository access…');
  try{
   const result=await publishWebsite({token:token.trim(),content,base:saved,onProgress:setPublishProgress});
   latestPublished.current=result.content;setContent(result.content);setSaved(result.content);setHistory([]);setCommitUrl(result.commitUrl);setPublishOpen(false);
   toast.success('Saved to GitHub. The public website will update when GitHub Pages finishes deploying.',{duration:10000});
  }catch(e){setPublishError(e instanceof Error?e.message:'Publishing failed. Your saved draft is still available.');}
  finally{setPublishing(false);setPublishProgress('');}
 }
 async function discard(){
  if(discarding)return;setDiscarding(true);
  try{await clearDraft();restoreFailed.current=false;const published=structuredClone(latestPublished.current);setContent(published);setSaved(published);setHistory([]);setDiscardOpen(false);setCommitUrl('');toast('Draft replaced with the latest loaded published version.');}
  catch{toast.error('The draft could not be cleared. Please try again.');}
  finally{setDiscarding(false);}
 }
 function applyForm(){if(!form)return;let next=content;if(form.kind==='profile'){next={...form.value,sections:content.sections};}else if(form.kind==='section'){next={...content,sections:form.isNew?[...content.sections,form.value]:content.sections.map(s=>s.id===form.value.id?form.value:s)};}else{next={...content,sections:content.sections.map(s=>s.id===form.section?{...s,items:form.isNew?[...s.items,form.value]:s.items.map(i=>i.id===form.value.id?form.value:i)}:s)};}const checked=siteSchema.safeParse(next);if(!checked.success){toast.error('Check your content lengths and links. Website links must start with https://.');return;}change(checked.data);setForm(null);}
 function updateForm(key:string,value:unknown){setForm(f=>f?{...f,value:{...f.value,[key]:value}} as Form:f);}
 async function upload(f:File){if(!form)return;if(form.kind==='profile'&&!f.type.startsWith('image/')){toast.error('Choose an image for the portrait.');return;}setUploading(true);try{const d=await stageMedia(f);setForm(current=>{if(!current)return null;if(current.kind==='profile')return {...current,value:{...current.value,portrait:d.url}};if(current.kind==='item')return {...current,value:{...current.value,media:d.url,mediaType:d.type}};return current;});toast.success('Photo or media selected. Save changes to keep it in your draft.');}catch(e){toast.error(e instanceof Error?e.message:'File could not be added.');}finally{setUploading(false);}}
 useEffect(()=>{
  const context=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:unknown)=>void|Promise<void>}}).modelContext;if(!context)return;const lifecycle=new AbortController();
  try{void Promise.resolve(context.registerTool({name:'read_portfolio',description:'Read the currently visible academic portfolio and whether the editor is open.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>({content:stateRef.current.content,editing:stateRef.current.editing})},{signal:lifecycle.signal})).catch(e=>console.warn('Agent tools unavailable',e));
   if(canEdit)void Promise.resolve(context.registerTool({name:'start_portfolio_editing',description:'Open the portfolio editor. Does not change or save content.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('Expected an empty object.');setEditing(true);return {editor:'open',saved:false};}},{signal:lifecycle.signal})).catch(e=>console.warn('Agent tools unavailable',e));
  }catch(e){console.warn('Agent tools unavailable',e);}return()=>lifecycle.abort();
 },[canEdit]);
 return <><Toaster position="bottom-right"/><a className="skip-link" href="#main">Skip to content</a><div className="topbar"><a href="./" className="wordmark" onClick={canEdit?e=>{e.preventDefault();navigate('home');}:undefined}>LC<span> / Liuyang Cheng</span></a><nav aria-label="Main navigation"><a href="./" aria-current={page==='home'?'page':undefined} onClick={canEdit?e=>{e.preventDefault();navigate('home');}:undefined}>Home</a><a href="./research.html" aria-current={page==='research'?'page':undefined} onClick={canEdit?e=>{e.preventDefault();navigate('research');}:undefined}>Research</a><a href="./#publications" onClick={canEdit?e=>{e.preventDefault();navigate('home','publications');}:undefined}>Publications</a></nav>{canEdit?<button className="edit-toggle" disabled={!loaded} onClick={()=>setEditing(e=>!e)}>{editing?<Eye size={14}/>:<Pencil size={14}/>} {editing?'Preview':'Edit page'}</button>:<a className="editor-signin" href={'./editor.html'+(page==='research'?'?page=research':'')}>Edit website</a>}</div>
 {canEdit&&<div className="editor-bar"><div><strong>{editing?'Editing your website':'Previewing your changes'}</strong><span role="status" aria-live="polite">{draftStatus==='saving'?'Saving draft…':draftStatus==='error'?'Draft could not be saved':dirty?'Draft saved on this device · not published':commitUrl?'Saved to GitHub':'No unpublished changes'}</span></div><div className="editor-actions">{editing&&loaded&&<><button onClick={()=>{const last=history.at(-1);if(last){setDraftStatus('saving');setContent(last);setHistory(h=>h.slice(0,-1));}}} disabled={!history.length||saving||publishing}><Undo2 size={15}/>Undo</button><button disabled={!loaded||publishing} onClick={()=>setForm({kind:'section',value:{id:crypto.randomUUID(),title:page==='research'?'New project':'New section',intro:'',page,items:[]},isNew:true})}><Plus size={15}/>{page==='research'?'Project':'Section'}</button></>}<button onClick={save} disabled={!loaded||saving||publishing}>{saving?'Preparing…':'Download backup'}</button>{(dirty||draftStatus==='error')&&<button disabled={publishing} onClick={()=>setDiscardOpen(true)}>Discard draft</button>}<Button onClick={()=>{setPublishError('');setPublishOpen(true);}} disabled={!loaded||publishing||saving||!dirty}><Check size={14}/>{publishing?'Saving…':'Save to GitHub'}</Button></div>{editing&&loaded&&<p>Changes and uploaded photos are saved on this device. Use Save to GitHub to update the public website. Drag the handles or use the arrows to rearrange entries.</p>}{draftError&&<p className="draft-error" role="alert">{draftError}</p>}{commitUrl&&<p>Changes committed. <a href={commitUrl} target="_blank" rel="noopener noreferrer">View the saved version on GitHub</a> · <a href="https://github.com/LiuyangMechSE/liuyangmechse.github.io/actions" target="_blank" rel="noopener noreferrer">Check deployment</a></p>}</div>}
 <Dialog open={publishOpen} onOpenChange={open=>{if(!publishing)setPublishOpen(open);}}><DialogContent className="edit-dialog publish-dialog"><DialogHeader><DialogTitle>Save your website to GitHub</DialogTitle><DialogDescription>This publishes your changes to LiuyangMechSE/liuyangmechse.github.io so visitors can see them.</DialogDescription></DialogHeader><form className="edit-form" onSubmit={e=>{e.preventDefault();void publish();}}><p>Authorize saving with a GitHub fine-grained personal access token. Select only <strong>liuyangmechse.github.io</strong> and set <strong>Contents → Read and write</strong>.</p><a href="https://github.com/settings/personal-access-tokens/new" target="_blank" rel="noopener noreferrer">Create a repository access token on GitHub</a><label className="field"><span>GitHub access token</span><Input type="password" value={token} onChange={e=>setToken(e.target.value)} autoComplete="off" autoCapitalize="none" spellCheck={false} placeholder="Paste your token here" required disabled={publishing}/></label><p className="authorization-note">Authorization stays in this tab and is never stored with your draft or published files. Closing or refreshing the page clears it.</p>{publishError&&<p role="alert" className="publish-error">{publishError}</p>}{publishing&&<p role="status">{publishProgress}</p>}<div className="form-actions"><button type="button" disabled={publishing} onClick={()=>setPublishOpen(false)}>Cancel</button><Button type="submit" disabled={publishing||!token.trim()}>{publishing?'Saving to GitHub…':'Save to GitHub'}</Button></div></form></DialogContent></Dialog>
 <Dialog open={discardOpen} onOpenChange={open=>{if(!discarding)setDiscardOpen(open);}}><DialogContent><DialogHeader><DialogTitle>Discard your saved draft?</DialogTitle><DialogDescription>This replaces your local edits with the latest published version loaded by the editor. Download a backup first if you want to keep them.</DialogDescription></DialogHeader><div className="form-actions"><button disabled={discarding} onClick={()=>setDiscardOpen(false)}>Keep draft</button><Button disabled={discarding} onClick={discard}>{discarding?'Discarding…':'Discard draft'}</Button></div></DialogContent></Dialog>

 <main id="main" className={'page '+(page==='research'?'research-page ':'')+(editing?'editing':'')} aria-busy={!loaded&&!loadError}>{loadError?<div className="load-error" role="alert">{loadError}<button onClick={load}>Retry</button></div>:!loaded&&<p className="loading-note">Loading website…</p>}
 {page==='home'?<header className={'intro '+(content.portrait?'with-portrait':'')}><div><p className="research-field">{content.field}</p><h1>{content.name}</h1><p className="affiliation">{content.affiliation}</p><div className="bio">{content.bio.split('\n\n').map((p,i)=><p key={i}>{p}</p>)}</div><Links links={content.links}/>{editing&&loaded&&<button className="inline-edit" onClick={()=>setForm({kind:'profile',value:structuredClone(content)})}><Pencil size={14}/>Edit introduction & links</button>}</div>{content.portrait&&<img className="portrait" src={mediaSource(content.portrait)} alt={content.name}/>}</header>:<header className="research-intro"><p className="research-field">{content.name}</p><h1>Research</h1><p>Projects in material mechanics and soft robotics, with interactive demonstrations and figures from the papers.</p><nav aria-label="Research projects">{visibleSections.map(s=><a key={s.id} href={'#'+s.id}>{s.title}</a>)}</nav></header>}
 {visibleSections.map((section,si)=><section id={section.id} data-section={section.id} key={section.id} className={'content-section '+(drop===section.id?'drop-target ':'')+(dragging===section.id?'dragging':'')}><div className="section-heading"><h2>{section.title}</h2>{editing&&loaded&&<div className="section-tools">{grip('section',section.id)}<button className="icon-button" aria-label={'Move '+section.title+' up'} disabled={si===0} onClick={()=>moveSection(section.id,si-1)}><ArrowUp size={15}/></button><button className="icon-button" aria-label={'Move '+section.title+' down'} disabled={si===visibleSections.length-1} onClick={()=>moveSection(section.id,si+1)}><ArrowDown size={15}/></button><button className="icon-button" aria-label={'Edit '+section.title} onClick={()=>setForm({kind:'section',value:structuredClone(section)})}><Pencil size={15}/></button><button className="icon-button" aria-label={'Remove '+section.title} onClick={()=>{change({...content,sections:content.sections.filter(s=>s.id!==section.id)});toast('Section removed. Use Undo to restore it.');}}><Trash2 size={15}/></button></div>}</div>{section.intro&&<p className="section-intro">{section.intro}</p>}
 {section.items.map((item,ii)=>{const hasMedia=item.media||item.demo!=='none'||item.figure?.src;const paired=!!item.figure?.src&&(!!item.media||item.demo!=='none');const titleUrl=item.links.find(link=>link.url.startsWith('https://'))?.url;return <article key={item.id} data-item={item.id} className={`entry ${hasMedia?'has-media':'text-entry'} layout-${paired?'wide':item.layout} ${drop===item.id?'drop-target':''} ${dragging===item.id?'dragging':''}`}>{editing&&loaded&&<div className="entry-tools">{grip('item',item.id,section.id)}<button className="icon-button" aria-label={'Move '+item.title+' up'} disabled={ii===0} onClick={()=>moveItem(section.id,item.id,ii-1)}><ArrowUp size={14}/></button><button className="icon-button" aria-label={'Move '+item.title+' down'} disabled={ii===section.items.length-1} onClick={()=>moveItem(section.id,item.id,ii+1)}><ArrowDown size={14}/></button><button onClick={()=>setForm({kind:'item',value:structuredClone(item),section:section.id})}><Pencil size={13}/>Edit entry</button><button className="icon-button" aria-label={'Remove '+item.title} onClick={()=>{sectionChange(section.id,s=>({...s,items:s.items.filter(i=>i.id!==item.id)}));toast('Entry removed. Use Undo to restore it.');}}><Trash2 size={14}/></button></div>}{hasMedia&&<ProjectMedia item={item}/>}<div className="entry-copy">{hasMedia&&item.meta&&<p className="topic">{item.meta}</p>}<h3>{titleUrl?<a href={titleUrl} target="_blank" rel="noopener noreferrer">{item.title}</a>:item.title}</h3>{item.authors&&<p className="authors">{item.authors.split(/(Liuyang Cheng)/g).map((s,i)=>s==='Liuyang Cheng'?<strong key={i}>{s}</strong>:s)}</p>}{!hasMedia&&item.meta&&<p className="venue">{item.meta}</p>}{item.text&&<p className="entry-description">{item.text}</p>}<Links links={item.links}/></div></article>;})}
 {editing&&loaded&&<button className="add-entry" onClick={()=>setForm({kind:'item',section:section.id,value:blankItem(),isNew:true})}><Plus size={15}/>Add an entry</button>}
 </section>)}
 <footer><span>© {new Date().getFullYear()} {content.name}</span><a href="#">Back to top</a></footer></main>
 <Dialog open={!!form} onOpenChange={open=>{if(!open&&!uploading)setForm(null);}}><DialogContent className="edit-dialog"><DialogHeader><DialogTitle>{form?.kind==='profile'?'Edit introduction':form?.kind==='section'?'Edit section':'Edit research entry'}</DialogTitle><DialogDescription>Save changes to keep your draft on this device, then use Save to GitHub to publish it.</DialogDescription></DialogHeader>{form&&<form onSubmit={e=>{e.preventDefault();applyForm();}} className="edit-form">
 {form.kind==='profile'?<><Field label="Name" value={form.value.name} onChange={v=>updateForm('name',v)}/><Field label="Research areas" value={form.value.field} onChange={v=>updateForm('field',v)}/><Field label="Affiliation" value={form.value.affiliation} onChange={v=>updateForm('affiliation',v)}/><Field label="Biography" value={form.value.bio} multiline onChange={v=>updateForm('bio',v)}/></>:<><Field label="Title" value={form.value.title} onChange={v=>updateForm('title',v)}/>{form.kind==='section'?<><Choice label="Page" value={form.value.page} onChange={v=>updateForm('page',v)} options={[["home","Home"],["research","Research"]]}/><Field label="Section introduction" value={form.value.intro} multiline onChange={v=>updateForm('intro',v)}/></>:<><Field label="Description" value={form.value.text} multiline onChange={v=>updateForm('text',v)}/><Field label="Authors" value={form.value.authors} onChange={v=>updateForm('authors',v)}/><Field label="Topic or venue and year" value={form.value.meta} onChange={v=>updateForm('meta',v)}/><div className="form-columns"><Choice label="Animated demo" value={form.value.demo} onChange={v=>updateForm('demo',v)} options={[["none","No demo"],["antagonist","Opposing ligaments"],["joint","Rotating joint"],["running","Running leg"]]}/><Choice label="Media placement" value={form.value.figure?.src&&(form.value.media||form.value.demo!=='none')?'wide':form.value.layout} onChange={v=>updateForm('layout',v)} options={form.value.figure?.src&&(form.value.media||form.value.demo!=='none')?[["wide","Full width with paper figure"]]:[["left","Left of text"],["right","Right of text"],["wide","Full width"]]}/></div></>}</>}
 {form.kind!=='section'&&<><div className="media-upload" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const f=e.dataTransfer.files[0];if(f&&!uploading)void upload(f);}}><Upload size={21}/><strong>{form.kind==='profile'?'Portrait photo':'Image, GIF, or video'}</strong><span>Drop a file here or choose one · up to 25 MB</span><input ref={file} type="file" accept={form.kind==='profile'?'image/jpeg,image/png,image/webp,image/gif':'image/jpeg,image/png,image/webp,image/gif,video/mp4,video/webm'} hidden onChange={e=>{if(e.target.files?.[0])void upload(e.target.files[0]);e.target.value='';}}/><button type="button" disabled={uploading} onClick={()=>file.current?.click()}>{uploading?'Uploading…':'Choose file'}</button></div><Field label={form.kind==='profile'?'Portrait URL (optional)':'Media URL (optional; replaces the demo)'} value={form.kind==='profile'?form.value.portrait:form.value.media} onChange={v=>updateForm(form.kind==='profile'?'portrait':'media',v)}/>{form.kind==='item'&&<><Choice label="Media type" value={form.value.mediaType} onChange={v=>updateForm('mediaType',v)} options={[["image","Image / GIF"],["video","Video (MP4 / WebM)"]]}/><Field label="Caption / accessible description" value={form.value.caption} onChange={v=>updateForm('caption',v)}/></>}{form.kind==='item'&&<fieldset className="figure-editor"><legend>Paper figure beside the demo</legend>{(['src','alt','caption','sourceLabel','sourceUrl'] as const).map(key=><Field key={key} label={{src:'Figure image URL (optional)',alt:'Figure description',caption:'Figure caption',sourceLabel:'Source and manuscript version',sourceUrl:'Source paper URL (optional)'}[key]} value={form.value.figure?.[key]??''} onChange={v=>updateForm('figure',{src:'',alt:'',caption:'',sourceLabel:'',sourceUrl:'',...form.value.figure,[key]:v})}/>)}</fieldset>}<div className="link-editor"><h4>Links</h4>{form.kind==='item'&&<p style={{fontSize:12,color:'#617688',margin:'0 0 10px'}}>The first website link also opens from the title.</p>}{form.value.links.map((link,i)=><div className="link-row" key={i}><Input aria-label={'Link '+(i+1)+' label'} placeholder="Label, e.g. Paper" value={link.label} onChange={e=>updateForm('links',form.value.links.map((l,j)=>j===i?{...l,label:e.target.value}:l))}/><Input aria-label={'Link '+(i+1)+' URL'} placeholder="https://…" value={link.url} onChange={e=>updateForm('links',form.value.links.map((l,j)=>j===i?{...l,url:e.target.value}:l))}/><button type="button" className="icon-button" aria-label={'Remove link '+(i+1)} onClick={()=>updateForm('links',form.value.links.filter((_,j)=>j!==i))}><X size={14}/></button></div>)}<button type="button" disabled={form.value.links.length>=10} onClick={()=>updateForm('links',[...form.value.links,{label:'',url:''}])}><Plus size={14}/>Add link</button></div></>}
 <div className="form-actions"><button type="button" disabled={uploading} onClick={()=>setForm(null)}>Cancel</button><Button type="submit" disabled={uploading}>Save changes</Button></div></form>}</DialogContent></Dialog>
 </>;
}
